### ISSUE TITLE
Implement operating status sensors including current stage

### ISSUE THREAD

**Issue by celestinjr** [dahlb/ha_carrier#116]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Required to open app to see current compressor stage. 

### Describe the solution you'd like

Implement “Operating Status” sensors, particularly the current compressor stage. 

### Describe alternatives you've considered

Use vendor app. 

### Additional context

NA

**Comment by celestinjr** [comment]
Closed by 766b8d9a6532686ecbcf85056f46ce293717ced2

**Comment by MallocArray** [comment]
I upgraded to this new version that said it included 'airflow_cfm, indoor_unit_operational_status, and outdoor_unit_operational_status sensors' but I'm not seeing anything new when I look at the Sensors under the Entity.  I did have the configuration.yaml manual add for these sensors, but I thought from notes, these would natively appear.  Is that a false assumption?

![image](https://github.com/dahlb/ha_carrier/assets/9374884/e9e857cb-bd01-44c5-af69-fd46d9f324d0)

**Comment by dahlb** [comment]
check your logs and that your on the latest version, it should look like this
<img width="316" alt="Screenshot 2024-06-11 at 7 10 12 PM" src="https://github.com/dahlb/ha_carrier/assets/54117/a2fb1b69-d18c-4c1a-ac93-c0b9d957627e">

**Comment by MallocArray** [comment]
Thanks, I did a full restart of HA instead of the prompted Restart after HACS updated. Now I see the new sensors.

**Comment by scheelj** [comment]
Thank You for the Operating Status Sensor access.....this was the missing
link to my automations!
