### ISSUE TITLE
ODU is handled as a non-numeric variable (off+0-100), it should just be numeric

### ISSUE THREAD

**Issue by CSFFlame** [dahlb/ha_carrier#119]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Sort of, ODU/IDU is a technically numeric value (percentage of load of the Outdoor unit(ODU) or IDU)
HA is treating it as 101 different text states (I think), vs 0-100 numeric.

![image](https://github.com/dahlb/ha_carrier/assets/105515466/6f6ee786-64c4-4844-86e0-d21563630e46)

### Describe the solution you'd like

Please make ODU/IDU numeric

### Describe alternatives you've considered

It's not really breaking anything, so I can live with it if it's a pain, the integration is great.

### Additional context

The "IDU" is not reporting any data, and I don't know why, but it also doesn't matter to me.  Perhaps it's heatstrips or something I don't have installed.  I presume from the "Off" that it would exhibit the same issue.

**Comment by dahlb** [comment]
![Screenshot_20240616-122800](https://github.com/dahlb/ha_carrier/assets/54117/4415efc4-45c7-4428-b5a9-1d0f79012b01)
![Screenshot_20240616-122747](https://github.com/dahlb/ha_carrier/assets/54117/ff7780a5-781b-499e-809b-390b3da871fa)

Only some units provide numbers
