### ISSUE TITLE
IDO and ODU Status units

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#121]
The latest release had new IDO and ODU sensors. But it's not clear what units are they? Is it % or status codes?

**Comment by RichardUUU** [comment]
I've been using this integration for a couple of days. So far, my ODU Status reports: Off, Stage 2, Stage 4, and Stage 5. My IDU Status always reports: Off. I'd like to know if that's normal or if it should be reporting something else as well.

**Comment by dahlb** [comment]
> I've been using this integration for a couple of days. So far, my ODU Status reports: Off, Stage 2, Stage 4, and Stage 5. My IDU Status always reports: Off. I'd like to know if that's normal or if it should be reporting something else as well.

That's normal if you are somewhere hot or have a heat pump

**Comment by dahlb** [comment]
> The latest release had new IDO and ODU sensors. But it's not clear what units are they? Is it % or status codes?

Units are dependent on your carrier models
