### ISSUE TITLE
Humidifier Filter Life

### ISSUE THREAD

**Issue by Sazerak** [dahlb/ha_carrier#122]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The OEM app has the ability to show the Humidifier Filter Life, but this entity does not show up in the HA integration.

### Describe the solution you'd like

Would it be possible to add an entity for Humidifier Filter Life?

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by dahlb** [comment]
added in v1.24.0
