### ISSUE TITLE
One temperature if thermostat in cooling or heating mode

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#15]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

confusing. 
![image](https://user-images.githubusercontent.com/13375246/232667978-e19260c4-fac8-4136-9de0-63f1086b5979.png)

### Describe the solution you'd like
<img width="518" alt="image" src="https://user-images.githubusercontent.com/13375246/232668533-77fbda66-4cb9-4282-be08-f63b05b0be62.png">

If thermostat is in heating or cooling show only one set point (not both like in auto mode). 
Not sure is it's a bug but there are duplicating temperature setpoint (see first screenshot)

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by dahlb** [comment]
I agree this would be nice and is currently being tracked [https://github.com/home-assistant/architecture/issues/264](here) the solution is at the home assistant core level not something we can fix in this integration

**Comment by dahlb** [comment]
found the bug, should be fixed in 1.20.2

**Comment by myevit** [comment]
Confirm. Issues is no more. 
Thanks!
