### ISSUE TITLE
Set heat source

### ISSUE THREAD

**Issue by ve6rah** [dahlb/ha_carrier#165]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have an air source heat pump system with natural gas furnace. In the carrier app, I can tell it to use only the heat pump, only the natural gas furnace, or let the system decide.

### Describe the solution you'd like

I would like to be able to set this from within home assistant so that I can take advantage of whichever fuel source is more economical at the time.

### Describe alternatives you've considered

I'm not really seeing any alternatives here, apart from manually setting it, but because the price of my electricity varies throughout the day, I would have to manually set it multiple times a day.

### Additional context

Let me know if there's any information that I can help provide to make this happen.

**Comment by ve6rah** [comment]
Just to follow up, I'm not sure the details of the API, but I see a config key in the diagnostic data that appears to be relevant:
`"heatsource": "idu only",`

The three options on my system appear to be:
- idu only
- odu only
- system

These map to "gas heat only", "heat pump only", and "system in control" respectively on the official Carrier software.

Is it as simple as exposing an input_select for that?

Hope that's helpful, and it would be great if we could do this! 

Thanks again for the excellent work on this integration!

**Comment by Stomachbuzz** [comment]
I agree, this would be a worthwhile feature update, even if just for viewing purposes.
I'm pretty frugal and tolerant, living in the mid-Atlantic, and my modern system's heat pump component is pretty dang good. My secondary source is electric heat. As a result, I pretty much always have it locked to "heat pump only", but it still seems to sneak in a cheeky bit of electric heat under certain conditions.

I'll have to look into if my electric rate is dynamic...probably is by now.
Either way, I would probably only enable electric heat if the outside air temp is below a certain threshold or such.

**Comment by dahlb** [comment]
v1.26.0 adds heat_source as a extra state attribute for the climate entity

I'm thinking about how to expose being able to change this as the climate entity doesn't seem to have a multiselect out of the box, the only reference to aux is a toggle

**Comment by ve6rah** [comment]
Considering there are 3 possible states, I don't think a toggle will work well here. Why not just make it it's own input_select entity?

**Comment by dahlb** [comment]
select added in v1.27.0.  I wasn't able to figure out how to decide if somebody has a heat pump, likely carrier does it by model numbers which would be a lot to start tracking so I just left all three options for everybody.

**Comment by ve6rah** [comment]
> select added in v1.27.0. I wasn't able to figure out how to decide if somebody has a heat pump, likely carrier does it by model numbers which would be a lot to start tracking so I just left all three options for everybody.

I was about to tell you to just look at the odutype field, but then I realised that is "none" on mine despite having a heat pump, so I'm not sure what to say!

Thanks for doing this though!

**Comment by ve6rah** [comment]
> select added in v1.27.0. I wasn't able to figure out how to decide if somebody has a heat pump, likely carrier does it by model numbers which would be a lot to start tracking so I just left all three options for everybody.

There's a field called "odutype", if there's no heat pump it should be "none", I don't know the other options, mine is "varcaphp", but I suspect there's are other hp options as well for staged units.

Thanks for doing this though!

**Comment by dahlb** [comment]
mine says "ac2stg", but for now I can limit it to indoor and system unless the odutype == "varcaphp" until others open new tickets or comment here with other odutype values the need the outdoor only option

**Comment by ve6rah** [comment]
I think you mean unless it says none, correct?

**Comment by ve6rah** [comment]
I mean we should guess at some of the other staging, but without someone with one of the other types posting their their debug I don't know.

**Comment by ve6rah** [comment]
I was going to say just exclude anything with none, but I guess your point about AC also makes sense

**Comment by ve6rah** [comment]
You could also probably just look for the letters HP anywhere in the string, I'm sure that would be majority correct and deal with the edge cases in tickets 
On a side note, although my unit uses gas heat for the indoor unit, I'm not sure that that is universal, as there are other heat sources possible. Instead of a fixed string of "gas heat only", maybe it should be looking up the heat source from the "idusource" field?

**Comment by dahlb** [comment]
updated the idu label based on the idusource field's value in v1.27.2.

I'd rather wait for tickets then guessing for the odutype fields though.

**Comment by ve6rah** [comment]
Fair enough, I just figured if it contains the substring HP it should be a pretty safe bet. 
But I'll certainly defer to your expertise!
 
Thanks again for your hard work on this! I certainly appreciate it!
