### ISSUE TITLE
Cannot change temperature from UI. HA climate component retrieves temperature as 0.0

### ISSUE THREAD

**Issue by ashayh** [dahlb/ha_carrier#166]
## System Information

version | core-2024.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1477
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 6.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.9.0), Mosquitto broker (6.4.1), Zigbee2MQTT (1.42.0-2), Get HACS (1.3.1), File editor (5.8.0), Advanced SSH & Web Terminal (19.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 29, 2024 at 03:51
-- | --
current_recorder_run | December 9, 2024 at 12:02
estimated_db_size | 24.45 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Thanks for the work on this integration!

This HA install is new setup, 2 weeks old. I'm able to view my thermostats in the dashboard, but not able to change the temperature. I have 2 Carrier Infinitys added to HA via the ha_carrier addon. Both of them appear on the Overview page as seen here.

**I am not sure if this is an issue with the climate component or this add on.**

![image](https://github.com/user-attachments/assets/00b9fe45-69b4-48ee-a27e-8c085ea4c5c9)

When I try to change the temperature, I see this exception in the logs and UI:
![image](https://github.com/user-attachments/assets/c4b99b6a-ad9c-4cae-8558-c5cd3b8ff3c0)

```
Failed to perform the action climate/set_temperature. '<' not supported between instances of 'float' and 'NoneType'
```

The `async_service_temperature_set` function in  `/usr/src/homeassistant/homeassistant/components/climate/__init__.py` appears to retrieve the temp as `0.0`. 

### Reproduction steps

1. Change the temperature with the + or - buttons on the dashboard.
2. Exception pop up is seen on the web ui
3. Exception is seen in the logs.
...

### Debug logs

```text
https://gist.github.com/ashayh/408c5cf7841b5e3b266972b889f84e16
```

**Comment by jnrollins** [comment]
Also have this issue.

**Comment by steinah6** [comment]
Me too, some changes seem to work on the thermostat but not reflected in HA. Automation doesn’t work

**Comment by aserper** [comment]
+1 I'm experiencing the same thing

**Comment by dahlb** [comment]
<img width="1250" alt="Screenshot 2024-12-22 at 7 30 01 AM" src="https://github.com/user-attachments/assets/1ed1883d-a433-48ee-8a4b-525438f2f90d" />
can you please include a diagnostic report, from the integration menu, download diagnostics
I think one of your climate entities temperature attributes is None but I'm not sure which and it will be included in the diagnostics

**Comment by ashayh** [comment]
[config_entry-ha_carrier-01JDWZTDM9606JNP67NQRD93BA.json](https://github.com/user-attachments/files/18222752/config_entry-ha_carrier-01JDWZTDM9606JNP67NQRD93BA.json)

Here you go. LMK what else I can provide.

**Comment by dahlb** [comment]
try v[1.23.2](https://github.com/dahlb/ha_carrier/commit/0d318b01410b87a0d714f652c020a656e96bcf51) I think it fixes this issue.

thanks for the diagnostics, looks like this integration was depending on the utility event being configured on the thermostat for a min and max temperature but it didn't need to be so I removed that dependence in 1.23.2 :)

**Comment by ashayh** [comment]
@dahlb Indeed 1.24.0 does fix it...Thanks you!

**Comment by jnrollins** [comment]
Just want to confirm it worked for me also. Ty for the suggestion.
