### ISSUE TITLE
Humdifier %USED vs. %REMAINING (battery sensor type)

### ISSUE THREAD

**Issue by sshimko** [dahlb/ha_carrier#169]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The introduction of the humidifier feature in 6548814e7a339b71ecb89c0dd9c2cf365f8ea7fb tracking %USED is great thank you! It did start triggering my automatons and cards that detect low batteries in devices though. I just replaced my steam humidifier cartridge and it is at 5% used. But, since it is a battery type sensor, it looks like it is low instead of high and is showing up on my low battery card and notifications sent via automation triggered by low battery sensor percentages.

So, the question is - should this sensor, as a battery type, really be 100% - %USED instead, i.e. should it really be %REMAINING? 

### Describe the solution you'd like

I think the battery sensor for humidifier %USED should be a negative offset from 100%, those it should show how much is remaining. This would be consistent with the concept of battery sensors where a lower percentage = less "life" left.

### Describe alternatives you've considered

This could be addressed via a template sensor, but then anyone that has setups to monitor low battery devices will need to both ignore this specific entity in their automation/cards/etc and create the template to make it a negative offset from 100. Or, there could be two exposed, one that is %USED and one that is %REMAINING, but if they're both battery types then people still have to ignore the %USED one.

### Additional context

<img width="508" alt="Screenshot 2024-12-23 at 9 28 34 AM" src="https://github.com/user-attachments/assets/c6567273-26c7-49ef-8ed6-dfef553c4777" />

**Comment by dahlb** [comment]
fixed in v1.26.2.

I got my battery warning today and couldn't agree more :)
