### ISSUE TITLE
custom integration 'ha_carrier' sets option flow config_entry explicitly

### ISSUE THREAD

**Issue by Motya-HA** [dahlb/ha_carrier#173]
## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4989
Installed Version | 2.0.1
Stage | running
Available Repositories | 1494
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 7, 2025 at 5:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-11.ui.nabu.casa
certificate_status | ready
instance_id | 28fee74463824ce68cf6f59a002a78bd
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 228.9 GB
disk_used | 63.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.6.1), MariaDB (2.7.1), File editor (5.8.0), Let's Encrypt (5.2.10), Advanced SSH & Web Terminal (19.0.0), Z-Wave JS UI (3.18.0), Mosquitto broker (6.4.1), InfluxDB (5.0.1), Nsupdate (1.0.5), Grafana (10.2.2), Dnsmasq (1.8.1), Auto Guest Login (1.4.0), Home Assistant Google Drive Backup (0.112.1), Silicon Labs Multiprotocol (2.4.5), Zigbee2MQTT (1.42.0-2), Zigbee2MQTT (1.42.0-2), TubesZB TI CC2652 FW Flasher (0.3.5.2), EMQX (0.7.2), ESPHome Device Builder (2024.12.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 17
views | 61
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 18, 2024 at 2:47 PM
-- | --
current_recorder_run | December 29, 2024 at 6:38 PM
estimated_db_size | 4405.66 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Error in log file related to integration

### Reproduction steps

1. Exists all the time in the log file
2.
3.
...

### Debug logs

```text
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 6:51:59 PM (1 occurrences)
Last logged: 6:51:59 PM

Detected that custom integration 'ha_carrier' sets option flow config_entry explicitly, which is deprecated at custom_components/ha_carrier/config_flow.py, line 35: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/dahlb/ha_carrier/issues
```

### Diagnostics dump

[config_entry-ha_carrier-01J4Q2EPG07D35SX815ECX5TQJ.json](https://github.com/user-attachments/files/18271754/config_entry-ha_carrier-01J4Q2EPG07D35SX815ECX5TQJ.json)

**Comment by dahlb** [comment]
thanks for writing this up
