### ISSUE TITLE
Update interval is not respected

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#21]
## System Information

version | core-2023.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Edmonton
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4917
Installed Version | 1.32.1
Stage | running
Available Repositories | 1280
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 28.5 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), AdGuard Home (4.8.6), Matter Server (4.3.1), Let's Encrypt (4.12.8), NGINX Home Assistant SSL proxy (3.4.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1 May 2023 at 04:55
-- | --
current_recorder_run | 5 May 2023 at 17:05
estimated_db_size | 217.36 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Status update is seems random. I have it set on 1 min refresh interval. Not sure if it's related to integration or it's laggy Carrier api.
<img width="576" alt="Screenshot 2023-05-07 at 15 13 25" src="https://user-images.githubusercontent.com/13375246/236702865-768e244f-cea4-4729-a47e-6e6c7f674b98.png">

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
N/A
```

**Comment by dahlb** [comment]
you are confusing the interval the integration updates from the API with the interval the API is updated by the thermostat, the integration can only control the first which is why it provides a sensor to track the second
