### ISSUE TITLE
Equipment sensor

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#22]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [ ] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not knowing which equipment is running

### Describe the solution you'd like

Would be nice to see if fan if running (which speed) or if heatpump or furnace is heating.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by dahlb** [comment]
multiple issues listed here,
speed of fan is already on the climate entity, listed as airflow_cfm: 0

heatpump or furnance might be provided on the climate entity as indoor_unit_operational_status: 'off'

if you would like another sensor please find it by downloading the diagnostics of the integration device, it has a json of all the api raw data and if you can find a field that has the data you would like exposed feel free to open a ticket to discuss which fields you would like exposed and how
