### ISSUE TITLE
Change filter icon to mdi:air-filter

### ISSUE THREAD

**Issue by deviantintegral** [dahlb/ha_carrier#25]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I was surprised to see the air filter life remaining exposed as a "battery". However, it's clear from https://github.com/dahlb/ha_carrier/blob/cd4925a8b0745063f175c23363e2d40800aa24c3/custom_components/ha_carrier/sensor.py#L156-L160 this is intentional. Looking at https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes, I suppose it really is the best class to use.

### Describe the solution you'd like

Can we set the default icon to `mdi:air-filter` instead of the battery? that will make it so a default view in a dashboard of the filter entity at least matches what it is.

### Describe alternatives you've considered

I double checked to see if there other sensor classes to use instead.

### Additional context

What this looks like when you change the icon:

<img width="346" alt="image" src="https://github.com/dahlb/ha_carrier/assets/255023/31a63c60-f14b-4d76-95bd-13620eb74feb">

**Comment by dahlb** [comment]
fixed in 1.20.3, thanks
