### ISSUE TITLE
Hold duration

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#30]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

example: Setting Away by default set it with hold till next schedule event. 

### Describe the solution you'd like

In Carrier app there is possibility to set hold duration. Would be nice to have it in the integration

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by myevit** [comment]
Not exactly what I am looking for. I am trying to set it to away mode indefinitely. If I will leave home for a weekend I want to make automation to set it to away till home assistant detects my presence

**Comment by dahlb** [comment]
there is already a setting available to accomplish that, check the box for the integration setting to make your holds infinite

<img width="824" alt="Screenshot 2023-05-31 at 9 24 48 PM" src="https://github.com/dahlb/ha_carrier/assets/54117/5974a3e6-9b42-429d-86c8-f1f389fc68d7">
