### ISSUE TITLE
Workaround for sloppy Carrier developers. External temperature reporting in C but the value is actually F

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#31]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Oh those dev people...... they forgot to convert external temperature to C (metric is my/the-rest-of-the-world preference).
<img width="313" alt="Screenshot 2023-05-31 at 7 12 33 PM" src="https://github.com/dahlb/ha_carrier/assets/13375246/8167fb23-6537-4ae3-b5c4-e05d83c667d8">

### Describe the solution you'd like

just to be aware of

### Describe alternatives you've considered

I have tried to contact Carrier to report a bug.... but nothing.

### Additional context

n/a

**Comment by dahlb** [comment]
please attach your device diagnostics from the integration, the raw api data is needed to verify how to fix this

**Comment by myevit** [comment]
`2023-05-31 19:36:50.362 DEBUG (SyncWorker_4) [carrier_api.status] raw_status_json:{'$': {'version': '1.48', 'xmlns:atom': 'http://www.w3.org/2005/Atom'}, 'atom:link': [{'$': {'rel': 'self', 'href': 'https://www.app-api.ing.carrier.com/systems/2222W206659/status'}}, {'$': {'rel': 'http://www.api.ing.carrier.com/rels/system', 'href': 'https://www.app-api.ing.carrier.com/systems/xxxxxxxxxxxxx'}}], 'timestamp': '2023-06-01T01:36:22.426Z', 'pingRate': 15, 'iduStatusPingRate': 93600, 'iduFaultsPingRate': 86400, 'oduStatusPingRate': 90000, 'oduFaultsPingRate': 82800, 'historyPingRate': 75600, 'equipEventsPingRate': 79200, 'rootCausePingRate': 72000, 'serverHasChanges': True, 'configHasChanges': True, 'dealerHasChanges': True, 'dealerLogoHasChanges': False, 'oduConfigHasChanges': False, 'iduConfigHasChanges': False, 'utilityEventsHasChanges': False, 'sensorConfigHasChanges': False, 'sensorProfileHasChanges': False, 'sensorDiagnosticHasChanges': False, 'name': 'Thermostat', 'oat': 59, 'cfgem': 'C', 'vacatrunning': 'off', 'filtrlvl': 10, 'uvlvl': 13, 'humlvl': 3, 'ventlvl': 54, 'humid': 'off', 'localTime': '2023-05-31T19:36:22.426', 'oprstsmsg': 'idle', 'isDisconnected': False, 'idu': {'cfm': 426, 'opstat': 'off', 'type': 'furnacemodulating'}, 'odu': {'opmode': 'off', 'opstat': 'off', 'type': 'gs3ngiphp'}, 'isActive': False, 'zones': {'zone': [{'$': {'id': '1'}, 'name': 'Main Floor', 'enabled': 'on', 'currentActivity': 'home', 'rt': 23.5, 'rh': 53, 'fan': 'low', 'hold': 'off', 'htsp': 22, 'clsp': 24, 'otmr': None, 'zoneconditioning': 'idle', 'damperposition': 15, 'occupancy': 'unoccupied', 'occupancyOverride': 'off'}, {'$': {'id': '2'}, 'name': 'Zone 2', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '3'}, 'name': 'Zone 3', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '4'}, 'name': 'Zone 4', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '5'}, 'name': 'Zone 5', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '6'}, 'name': 'Zone 6', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '7'}, 'name': 'Zone 7', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '8'}, 'name': 'Zone 8', 'enabled': 'off', 'hold': 'off', 'otmr': None}]}}`

I assume **'oat': 59** is value

**Comment by dahlb** [comment]
1.20.4 should fix this

**Comment by myevit** [comment]
Perfect! All working. Thanks!
