### ISSUE TITLE
Integration showing wrong thermostat state after midnight

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#33]
## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Edmonton
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1278
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 9.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), AdGuard Home (4.8.10), Matter Server (4.6.1), Let's Encrypt (4.12.9), NGINX Home Assistant SSL proxy (3.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 16 June 2023 at 13:59
-- | --
current_recorder_run | 20 June 2023 at 20:45
estimated_db_size | 316.95 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have a scheduling enabled in my thermostat. 22:00 to 7:00 it's in sleep mode with lower temperature set points. Termostat works as expected 
![photo_2023-06-25 11 37 44](https://github.com/dahlb/ha_carrier/assets/13375246/8e706b90-e6d7-4508-8687-af75b4d29e8d)
While the integration showing  different picture after 00:00
<img width="1174" alt="Screenshot 2023-06-25 at 11 38 53 AM" src="https://github.com/dahlb/ha_carrier/assets/13375246/e6a40a18-9509-4b62-aa79-5ab931615874">

### Reproduction steps

N/A

### Debug logs

```text
N/A
```

**Comment by dahlb** [comment]
please attach debug level logs or diagnostics dumps from before, during, and after if possible

**Comment by myevit** [comment]
here is about 24 hours of logs.
By the way, carrier_api still posts serial info into the logs, including PIN and url..... probably needed to be sanitized... 
[carrier_api.log.zip](https://github.com/dahlb/ha_carrier/files/11877705/carrier_api.log.zip)
[ha_carrier.log.zip](https://github.com/dahlb/ha_carrier/files/11877706/ha_carrier.log.zip)

**Comment by dahlb** [comment]
thanks those logs were illuminating, but looks like it is a problem in the logic of the scheduling periods so I released 1.20.6 with improved ha_carrier.log entries that expose the results of the current logic. please update to 1.20.6 and attach the re log, just the ha_carrier.log is needed this time.

**Comment by myevit** [comment]
here is new log
[Archive.zip](https://github.com/dahlb/ha_carrier/files/11928708/Archive.zip)

**Comment by dahlb** [comment]
thanks for uploading those logs, I think I found the bug and it should be fixed in 1.20.7

**Comment by myevit** [comment]
Great! I will give it a go and let you know!
Thank for doing this!

**Comment by myevit** [comment]
Confirming all works as intended. 
thanks!
