### ISSUE TITLE
Can a vacation be set?

### ISSUE THREAD

**Issue by Snuffy2** [dahlb/ha_carrier#35]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I just begrudgingly switched from an ecobee to a Carrier Infinity Touch. I have it successfully connected to HA via your great integration. With the ecobee, I could [call a service](https://www.home-assistant.io/integrations/ecobee#service-ecobeecreate_vacation) to create a vacation on the thermostat. Is there any way to do this with ha_carrier?

### Describe the solution you'd like

A service or other method to programmatically set a vacation on the thermostat.

### Describe alternatives you've considered

If the API is posted somewhere and it is doable, I'd be willing to attempt a PR for it.

### Additional context

None

**Comment by dahlb** [comment]
you can do this using the service call exampled below
```
service: climate.set_preset_mode
data:
  preset_mode: vacation
target:
  entity_id: climate.hvac_zone_1
```

**Comment by Snuffy2** [comment]
Ok, but how can I set the start date/time, end date/time and desired vacation temperature(s)?

**Comment by dahlb** [comment]
you can use ha automations to use the manual mode and configure temperatures, or you can use the carrier app/thermostat to configure a static vacation mode and then use ha to invoke that vacation mode as defined above; configuring a static profile using the ha integration seems a waste as I don't understand a use case where it needs to be dynamic

**Comment by Snuffy2** [comment]
Not necessarily dynamic, just automated. Because I have baseboard heat, I have multiple smart thermostats in the house. I have automations in HA that identify when I'll be on vacation based on entires in a calendar and automatically put the thermostats in a vacation mode set to end when I get back.

**Comment by dahlb** [comment]
You can do that with by setting preset to vacation, the integration defaults to infinitely holding on preset change, then with another automation that triggers when you are expected to return use the preset 'resume' to resume your normal schedule
