### ISSUE TITLE
Operation Status

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#55]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

In the Carrier app there is a page with Operation Status. 
![IMG_3751](https://github.com/dahlb/ha_carrier/assets/13375246/a1824f65-7913-4040-a987-06ae05bdd01d)
In my automation I need to know if the fan is actually running, it should control my non-carrier heat recovery ventilator (furnace interlock).
Would be great to have those in hass!

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by dahlb** [comment]
![Screenshot_20230925-083141.png](https://github.com/dahlb/ha_carrier/assets/54117/a65720d2-a8e9-4447-9a92-76b6ad1acdd3)

Airflow cfm is already in the integration and tells you not only if the fan is on/off but how fast it is going.

**Comment by myevit** [comment]
Perfect!
Thanks!
