### ISSUE TITLE
Integration is reporting wrong active preset.

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#57]
## System Information

version | core-2023.9.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 5.15.107+truenas
arch | x86_64
timezone | America/Edmonton
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1294
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 6
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18 September 2023 at 19:55
-- | --
current_recorder_run | 26 September 2023 at 14:30
estimated_db_size | 271.63 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

it feels like Integration doesn't take into account timezone. 
sleep schedule should start at 20:00, but HASS showing it two hours ahead 
![IMG_3757](https://github.com/dahlb/ha_carrier/assets/13375246/20b6f528-953f-4638-aba0-e348bb6213ca)
![IMG_3758](https://github.com/dahlb/ha_carrier/assets/13375246/aa6e1fe3-55ab-40d3-9701-15acf80c5b0f)
![IMG_3759](https://github.com/dahlb/ha_carrier/assets/13375246/f6a2bbe7-1a05-4693-b5ea-d25f45d1a129)

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
n/a
```

**Comment by dahlb** [comment]
none of the carrier api properly handles timezones, the data is the api pretends utc is the current tz; that shouldn't really matter and to simplify matters even more I updated in https://github.com/dahlb/ha_carrier/commit/99177f83f2ca03b10818b83b552eaec53707275b to have the integration no longer even try to determine the current activity and instead just allow the api's status to provide what it is.
