### ISSUE TITLE
Add Sensors for current state

### ISSUE THREAD

**Issue by Bad-Magic** [dahlb/ha_carrier#60]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'd like to track how long my system is active, and preferably at what % the compressors are running.

### Describe the solution you'd like

Not sure of the limitations on the Carrier API side, but it would be great to have the current state(s) polled on update.

Is the compressor on?  What %?
Is the system actively heating? cooling?

### Describe alternatives you've considered

None

### Additional context

None

**Comment by FSFirenze** [comment]
This is cool, is there a full list of the informations available in the integration's climate entity?

**Comment by dahlb** [comment]
use the developer in home assistant and select the climate entity, you'll see something like this with everything listed
<img width="890" alt="Screenshot 2023-11-30 at 8 57 28 PM" src="https://github.com/dahlb/ha_carrier/assets/54117/5286353d-c663-4e15-b6d0-88db3e526c79">
