### ISSUE TITLE
Remote room temperature sensor

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#72]
Thank you for your integration!
My current issue is that when I have guest in the house, they are generating heat that affects thermostat temperature sensor and my further rooms showing 1-2 degree drop on average. It's cold where I live. Make sence.
I am not sure if carrier infinity system has wireless aux temperature sensors to make house average temperature that should be used in temperature control. I couldn't fing any. 
So, I wonder if there is a way to "hack" the temperature reading in the thermostat and adjust it or provide virtual temperature sensors from HASS, which I have all over the house.
Second option,probably will be making a blueprint - that average the temperature from selected sensors over the hour or so and adjust the once a house the infinity setpoint... 
What do you think?

**Comment by dahlb** [comment]
I believe carrier only allowed a single sensor, local at the thermostat or hard wired remote.

I feel when the temperature isn't even it's more of an airflow issue then heating issue, might be better to adjust fan speed or air dampeners.

However if you want to use off the shelf temperature sensors, and a blue print to adjust the thermostat; good luck but this integration can't help you build it.
