### ISSUE TITLE
Status of Preset never changes in HA

### ISSUE THREAD

**Issue by gokou340** [dahlb/ha_carrier#86]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4836
Installed Version | 1.34.0
Stage | running
Available Repositories | 1381
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 14.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), File editor (5.7.0), Z-Wave JS UI (3.3.0), RPC Shutdown (2.4), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.1-1), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 23, 2024 at 6:07 PM
-- | --
current_recorder_run | February 3, 2024 at 1:41 PM
estimated_db_size | 213.75 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 0 / 2
local_online | 2 / 2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When selecting a Preset such as Home, Away or Sleep, nothing happens in Home Assistant. It will change back to "Home".

For example, if the current preset is Home, I select Away, but nothing changes. The preset changes back to "Home". If I look in the Carrier app after a few minutes, it will say "Holding Away", but HA continues to say that it is currently "Home" with the temperatures of the Home profile

### Reproduction steps

1. Select different preset such as Away or Sleep
2. Nothing changes in Home Assistant
3. Carrier app shows "Holding Away" or "Holding Sleep"
...

### Debug logs

```text
Won't let me submit. Says that the body is too long
```

**Comment by dahlb** [comment]
sorry, when I tried to reproduce the preset updates in my instance of ha, going to need your logs to have any idea what's going on in this issue

**Comment by gokou340** [comment]
Will do, when the issue occurs again, I will get some logs!
