### ISSUE TITLE
2024.2 warning about on/off

### ISSUE THREAD

**Issue by OwlSaver** [dahlb/ha_carrier#89]
### System Health details

Entity None (<class 'custom_components.ha_carrier.climate.Thermostat'>) implements HVACMode(s): off, fan_only, heat_cool, heat, cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/dahlb/ha_carrier/issues

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

It just showed up in my log. So, I am doing what it said.

### Reproduction steps

1.Look in the log.
2.
3.
...

### Debug logs

```text
No idea.
```

**Comment by dahlb** [comment]
fixed in https://github.com/dahlb/ha_carrier/commit/d92b6c53df8d2a1e2fc2e0fff3fb3548bcdb6b59

**Comment by dahlb** [comment]
fixed in v[1.21.4](https://github.com/dahlb/ha_carrier/commit/eb21288eb5f00e94260689d5c2d0785a675afe5f)
