### ISSUE TITLE
Where do you log in?

### ISSUE THREAD

**Issue by mmoceri4888** [dahlb/ha_carrier#96]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.45
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1468
Downloaded Repositories | 10
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 23, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-4.ui.nabu.casa
certificate_status | ready
instance_id | ad20525e66ce43c6bae9a1a985cbbba1
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 13.6 GB
disk_used | 6.7 GB
healthy | true
supported | failed to load: Unsupported
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Z-Wave JS (0.4.4), Terminal & SSH (9.9.0), Mosquitto broker (6.1.2), Portainer (2.19.4-3), Home Assistant Google Drive Backup (0.108.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 3
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 15, 2024 at 9:00 AM
-- | --
current_recorder_run | February 22, 2024 at 5:04 AM
estimated_db_size | 115.11 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Not seeing where to login with my carrier credentials.

### Reproduction steps

1. Installed through HACS
2.
3.
...

### Debug logs

```text
Test
```

**Comment by dahlb** [comment]
you're missing step 2, go to settings/devices and services click "add integration" select "carrier infinity"
